build:
	sudo add-apt-repository ppa:webupd8team/java
	sudo apt-get update
	sudo apt-get install oracle-java8-installer

compile: add.java
	javac add.java

execute: add.class
	java add

clean:
	rm *.class
